name: Build Windows Forms App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1

    - name: Restore NuGet packages
      run: nuget restore WindowsFormsApp1.sln

    - name: Build the application
      run: msbuild WindowsFormsApp1.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: YTDownloader
        path: |
          bin/Release/WindowsFormsApp1.exe
          bin/Release/yt-dlp.exe
          bin/Release/*.dll